name: ratfish
description: "Catfish eachother!"

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.1.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  pointycastle: ^3.9.1
  shared_preferences: ^2.3.2
  http: ^1.2.2
  image_picker: ^1.1.2
  image: ^3.0.1
  chatview: ^2.2.0
  path_provider: ^2.1.4
  ffmpeg_kit_flutter: 6.0.3-LTS

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
